apiVersion: castopod.kopilote.io/v1beta1
kind: Configuration
metadata:
  name: default
spec:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: dns-letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  media:
    bucket: castopod-content
    endpoint: https://s3.fr-par.scw.cloud
    key: SCWDMX31ZKQ71XQ9QNEE
    region: fr-par
    secret: 6a8ccf6c-c904-46a5-a853-1a8b3c737932
  mysql:
    host: 51.159.26.243
    password: 642rcZFn6UHM4dkzL5@
    port: '8001'
    username: castopod
  smtp:
    from: no-reply@castopod.com
    host: mail.adaures.com
    password: '%H%kdqZLV%vzsD%!W#wD^zeGH46vrY6a'
    port: '587'
    username: no-reply@castopod.com
---
apiVersion: castopod.kopilote.io/v1beta1
kind: Version
metadata:
  name: default
spec:
  imageTag: 1.3.2
---
apiVersion: castopod.kopilote.io/v1beta1
kind: Version
metadata:
  name: default2
spec:
  imageTag: 1.3.2
---
apiVersion: castopod.kopilote.io/v1beta1
kind: Castopod
metadata:
  name: example
spec:
  configurationSpec: default
  versionSpec: default2
  activated: false
  config:
    url:
      base: castopod.192.168.1.3.nip.io
      media: castopod.192.168.1.3.nip.io
      legalNotice: castopod.192.168.1.3.nip.io
    limit:
      storage: "100"
    gateway:
      admin: /admin
      auth: /auth
      install: /install