# permissions for end users to edit castopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: castopod-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: castopod-editor-role
rules:
- apiGroups:
  - castopod.kopilote.io
  resources:
  - castopods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - castopod.kopilote.io
  resources:
  - castopods/status
  verbs:
  - get
